### ISSUE TITLE
Crashes with Ulauncher 5.8 

### ISSUE THREAD

**Issue by brunetton** [Ulauncher/ulauncher-emoji#23]
Hi

Since I upgraded to Ulauncher 5.8 the extension crashes. I'm missing it a lot ! This is clearly the extension I use the most and I'm missing it a lot !
Do you plan to fix the problem ? (ie: do you use it yourself ?)

Thanks a lot

**Comment by gornostal** [comment]
Sorry for the late reply.
The plugin works with the latest version.
Feel free to reopen if it doesn't work for you.

**Comment by brunetton** [comment]
Thanks. Indeed after updating from 5.8 to [5.14.3](https://github.com/Ulauncher/Ulauncher/releases/tag/5.14.3) this works now :partying_face:
