### ISSUE TITLE
No emoji output

### ISSUE THREAD

**Issue by Knut0730** [Ulauncher/ulauncher-emoji#24]
When typing `em smile` + `enter` there is no emoji output. (It should show a smiling cat)

LibreOffice Writer and Firefox both are not working.

edit: it seems like the emoji gets copied instead of just inserted, I hope this is an error, because it is pretty tedious.

**Comment by imabp** [comment]
yes it gets copied.

**Comment by gornostal** [comment]
Sorry for a late reply.
That's the expected behavior.
