### ISSUE TITLE
Search by alternative names

### ISSUE THREAD

**Issue by ledenis** [Ulauncher/ulauncher-emoji#27]
It would be nice if we could search by some alternative names, so we could easily find the emoji even if we don't know the official or shortcode.

For example, to find 🌎 or 🌍, one has to search with "globe" or ":earth" (strangely it does not show the one with europe with ":earth")
but not "world" or "planet" or even "earth" (without colon)

Maybe we could use the "Also Known As" data from emojipedia: https://emojipedia.org/globe-showing-europe-africa#technical ?

Thanks

**Comment by ledenis** [comment]
So I looked into the emoji.sqlite database and I see there are already the alternative names in the `name_search` column:

```
SELECT code, name_search FROM emoji WHERE name_search LIKE '%world%';
```
Result:
```
code | name_search
-- | --
🌍 | globe showing earth Europe-Africa Europe world Africa
🌎 | globe showing earth Americas globe_showing_americas world earth_americas
🌏 | globe showing earth Asia-Australia Australia Asia world
🌐 | globe earth meridians globe_with_meridians with world
🗺 | world world_map map
```

Is there a reason why `name_search` is not used?

**Comment by gornostal** [comment]
Apologies for the delayed response.
I don't remember intentionally ignoring the name_search field, so there's no reason not to use it, I suppose.

And yes, that would be a good feature.

I'll try to implement it when I get to that. Unless you or someone else will want to do that sooner.

Thanks for bringing my attention to this!

**Comment by gornostal** [comment]
@ledenis it's fixed now.
Bit thanks to @Laurens256 for implementing it!

**Comment by ledenis** [comment]
Great, thanks @Laurens256 !
