### ISSUE TITLE
Palestinans are not terrorists

### ISSUE THREAD

**Issue by ahmad-kashkoush** [Ulauncher/ulauncher-emoji#28]
I was just opening flag emojies and found out that you call palestine flag ``terrorists``.
innocent people are killed there and you called the palestinian flag terrorits this hurts me .

I don't ask for you to like them I'm asking you to remove terrorist word 
![image](https://github.com/Ulauncher/ulauncher-emoji/assets/89735230/84d07ab7-720a-448a-9187-f132b238d202)

**Comment by gornostal** [comment]
Hi Ahmad
Hope you're safe!

The text says territories not terrorists.

**Comment by ahmad-kashkoush** [comment]
oh😅, sorry for wasting your time.

**Comment by gornostal** [comment]
No worries

**Comment by summertaiyuan** [comment]
hhh
