### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by SanjayVyas** [Ulauncher/ulauncher-emoji#4]
I can bring up the emojis, but apart from seeing them, I find no way to insert them or use them in any app

**Comment by gornostal** [comment]
Once you select an emoji it'll be added to your clipboard. Then paste it anywhere with Ctrl+V or Shift+Ins
Have you tried that?

**Comment by SanjayVyas** [comment]
Oops... that's the only thing I didn't try. I thought upon selecting, it would insert in the current app. Thanks :+1:
