### ISSUE TITLE
Provide more emoji icon packs for opinionated users

### ISSUE THREAD

**Issue by MyriaCore** [Ulauncher/ulauncher-emoji#6]
I think a big step would be to offer [twemoji](https://github.com/twitter/twemoji) and [noto-emoji](https://github.com/googlefonts/noto-emoji), as those are the most common emoji packs used. 

We could have a settings menu setting to manage which style of emoji the user prefers, and keep the default on 'apple' (the style of emojis being used now).

**Comment by MyriaCore** [comment]
I'm I'm hoping to deliver this feature via [my fork](https://github.com/MyriaCore/ulauncher-emoji/tree/emoji-packs). I'll submit a PR when it's close to being finished. @gornostal @branb do you want me to submit a WIP PR, or would you prefer if I only submit a PR when the code is ready for review?

**Comment by gornostal** [comment]
If you submit it when it's ready for review that will be fine.

**Comment by MyriaCore** [comment]
Got it, I might be able to PR by the end of the day! I just got this thing working with twemoji. There seem to be some caveats to blobmoji and noto-emoji, but twemoji support seems the strongest by far. 

![demo](https://user-images.githubusercontent.com/35076430/85951564-d79abd80-b931-11ea-8220-0239fa8f9dec.gif)

**Comment by MyriaCore** [comment]
@gornostal PR is live at #8
